// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcCDy6e0nmuYkGZrsw6GWdzq-zO4hKvag',
    appId: '1:379730681482:web:9d340a05d090c3e6a35773',
    messagingSenderId: '379730681482',
    projectId: 'food-delivery-mobile-6d0fe',
    authDomain: 'food-delivery-mobile-6d0fe.firebaseapp.com',
    storageBucket: 'food-delivery-mobile-6d0fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaR6d3jibcQHH50KlG5F8XneaOeGTZihk',
    appId: '1:379730681482:android:cb21fa5bf733a82ca35773',
    messagingSenderId: '379730681482',
    projectId: 'food-delivery-mobile-6d0fe',
    storageBucket: 'food-delivery-mobile-6d0fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm3GDWEHX_y37xrhz0Res9V5zutcOVYy8',
    appId: '1:379730681482:ios:d09ffb9e7920b73ba35773',
    messagingSenderId: '379730681482',
    projectId: 'food-delivery-mobile-6d0fe',
    storageBucket: 'food-delivery-mobile-6d0fe.firebasestorage.app',
    iosBundleId: 'com.nomnomgo.foodDeliveryMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm3GDWEHX_y37xrhz0Res9V5zutcOVYy8',
    appId: '1:379730681482:ios:d09ffb9e7920b73ba35773',
    messagingSenderId: '379730681482',
    projectId: 'food-delivery-mobile-6d0fe',
    storageBucket: 'food-delivery-mobile-6d0fe.firebasestorage.app',
    iosBundleId: 'com.nomnomgo.foodDeliveryMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcCDy6e0nmuYkGZrsw6GWdzq-zO4hKvag',
    appId: '1:379730681482:web:1bfe6f026c931e2ca35773',
    messagingSenderId: '379730681482',
    projectId: 'food-delivery-mobile-6d0fe',
    authDomain: 'food-delivery-mobile-6d0fe.firebaseapp.com',
    storageBucket: 'food-delivery-mobile-6d0fe.firebasestorage.app',
  );
}
